const mongoose = require('mongoose');

const notificationSchema = new mongoose.Schema({
  // Thông tin cơ bản
  title: {
    type: String,
    required: true,
    trim: true,
    maxlength: 200
  },
  message: {
    type: String,
    required: true,
    maxlength: 1000
  },
  
  // Loại thông báo
  type: {
    type: String,
    enum: [
      'SYSTEM',           // Thông báo hệ thống
      'BATCH_UPDATE',     // Cập nhật lô thuốc
      'TRANSFER',         // Chuyển giao
      'QUALITY_ALERT',    // Cảnh báo chất lượng
      'EXPIRY_WARNING',   // Cảnh báo hết hạn
      'RECALL',           // Thu hồi
      'TASK_ASSIGNED',    // Giao nhiệm vụ
      'TASK_COMPLETED',   // Hoàn thành nhiệm vụ
      'COMPLIANCE_ALERT', // Cảnh báo tuân thủ
      'VERIFICATION',     // Xác thực
      'GENERAL'           // Thông báo chung
    ],
    required: true
  },
  
  // Mức độ ưu tiên
  priority: {
    type: String,
    enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
    default: 'MEDIUM'
  },
  
  // Người gửi
  sender: {
    walletAddress: {
      type: String,
      required: true,
      match: /^0x[a-fA-F0-9]{40}$/
    },
    name: String,
    role: String
  },
  
  // Người nhận
  recipients: [{
    walletAddress: {
      type: String,
      required: true,
      match: /^0x[a-fA-F0-9]{40}$/
    },
    name: String,
    role: String,
    readAt: Date,
    isRead: {
      type: Boolean,
      default: false
    }
  }],
  
  // Gửi theo nhóm
  targetGroups: [{
    type: String,
    enum: ['ALL', 'ADMIN', 'MANUFACTURER', 'DISTRIBUTOR', 'HOSPITAL', 'PATIENT']
  }],
  
  // Liên kết với đối tượng khác
  relatedEntity: {
    type: {
      type: String,
      enum: ['BATCH', 'TASK', 'USER', 'SUPPLY_CHAIN_EVENT']
    },
    id: mongoose.Schema.Types.Mixed,
    reference: String
  },
  
  // Nội dung chi tiết
  content: {
    shortDescription: String,
    longDescription: String,
    actionRequired: {
      type: Boolean,
      default: false
    },
    actionDeadline: Date,
    actionUrl: String,
    actionLabel: String
  },
  
  // Tệp đính kèm
  attachments: [{
    filename: String,
    originalName: String,
    mimetype: String,
    path: String,
    size: Number,
    uploadedAt: {
      type: Date,
      default: Date.now
    }
  }],
  
  // Cài đặt gửi
  deliverySettings: {
    channels: [{
      type: String,
      enum: ['IN_APP', 'EMAIL', 'SMS', 'PUSH'],
      enabled: {
        type: Boolean,
        default: true
      }
    }],
    scheduleTime: Date,
    expiryTime: Date,
    isScheduled: {
      type: Boolean,
      default: false
    }
  },
  
  // Trạng thái
  status: {
    type: String,
    enum: ['DRAFT', 'SENT', 'DELIVERED', 'READ', 'EXPIRED', 'CANCELLED'],
    default: 'DRAFT'
  },
  
  // Thống kê
  stats: {
    totalRecipients: {
      type: Number,
      default: 0
    },
    readCount: {
      type: Number,
      default: 0
    },
    deliveredCount: {
      type: Number,
      default: 0
    },
    lastReadAt: Date
  },
  
  // Metadata
  tags: [String],
  isPublic: {
    type: Boolean,
    default: false
  },
  isUrgent: {
    type: Boolean,
    default: false
  },
  category: String,
  
  // Auto-generated notifications
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  triggerEvent: String,
  
  // Approval workflow (for important notifications)
  requiresApproval: {
    type: Boolean,
    default: false
  },
  approvedBy: {
    walletAddress: String,
    name: String,
    approvedAt: Date
  },
  
  sentAt: Date,
  deliveredAt: Date
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Indexes
notificationSchema.index({ 'sender.walletAddress': 1 });
notificationSchema.index({ 'recipients.walletAddress': 1 });
notificationSchema.index({ type: 1 });
notificationSchema.index({ priority: 1 });
notificationSchema.index({ status: 1 });
notificationSchema.index({ 'relatedEntity.type': 1, 'relatedEntity.id': 1 });
notificationSchema.index({ targetGroups: 1 });
notificationSchema.index({ isPublic: 1 });
notificationSchema.index({ sentAt: -1 });

// Compound indexes
notificationSchema.index({ 'recipients.walletAddress': 1, 'recipients.isRead': 1 });
notificationSchema.index({ type: 1, sentAt: -1 });
notificationSchema.index({ priority: 1, status: 1 });

// Virtuals
notificationSchema.virtual('readPercentage').get(function() {
  if (this.stats.totalRecipients === 0) return 0;
  return Math.floor((this.stats.readCount / this.stats.totalRecipients) * 100);
});

notificationSchema.virtual('isExpired').get(function() {
  return this.deliverySettings.expiryTime && this.deliverySettings.expiryTime < new Date();
});

notificationSchema.virtual('timeUntilExpiry').get(function() {
  if (!this.deliverySettings.expiryTime) return null;
  const remaining = this.deliverySettings.expiryTime - new Date();
  return Math.max(0, Math.floor(remaining / (1000 * 60 * 60))); // hours
});

// Pre-save middleware
notificationSchema.pre('save', function(next) {
  // Set urgent flag for critical priority
  if (this.priority === 'CRITICAL') {
    this.isUrgent = true;
  }
  
  // Update stats
  this.stats.totalRecipients = this.recipients.length;
  this.stats.readCount = this.recipients.filter(r => r.isRead).length;
  
  // Auto-set sent date when status changes to SENT
  if (this.status === 'SENT' && !this.sentAt) {
    this.sentAt = new Date();
  }
  
  // Check expiry
  if (this.isExpired && this.status === 'SENT') {
    this.status = 'EXPIRED';
  }
  
  next();
});

// Static methods
notificationSchema.statics.findByRecipient = function(walletAddress) {
  return this.find({
    $or: [
      { 'recipients.walletAddress': walletAddress },
      { isPublic: true }
    ],
    status: { $in: ['SENT', 'DELIVERED', 'READ'] }
  }).sort({ sentAt: -1 });
};

notificationSchema.statics.findUnreadByRecipient = function(walletAddress) {
  return this.find({
    'recipients': {
      $elemMatch: {
        walletAddress: walletAddress,
        isRead: false
      }
    },
    status: { $in: ['SENT', 'DELIVERED'] }
  }).sort({ sentAt: -1 });
};

notificationSchema.statics.findBySender = function(walletAddress) {
  return this.find({ 'sender.walletAddress': walletAddress }).sort({ sentAt: -1 });
};

notificationSchema.statics.findByType = function(type, limit = 50) {
  return this.find({ 
    type: type,
    status: { $in: ['SENT', 'DELIVERED', 'READ'] }
  })
  .sort({ sentAt: -1 })
  .limit(limit);
};

notificationSchema.statics.findUrgentNotifications = function() {
  return this.find({
    isUrgent: true,
    status: { $in: ['SENT', 'DELIVERED'] }
  }).sort({ sentAt: -1 });
};

notificationSchema.statics.getNotificationStats = function(walletAddress) {
  return this.aggregate([
    {
      $match: {
        'recipients.walletAddress': walletAddress
      }
    },
    {
      $group: {
        _id: '$type',
        total: { $sum: 1 },
        unread: {
          $sum: {
            $cond: [
              { $in: [false, '$recipients.isRead'] },
              1,
              0
            ]
          }
        }
      }
    }
  ]);
};

// Instance methods
notificationSchema.methods.markAsRead = function(walletAddress) {
  const recipient = this.recipients.find(r => r.walletAddress === walletAddress);
  if (recipient && !recipient.isRead) {
    recipient.isRead = true;
    recipient.readAt = new Date();
    
    // Update stats
    this.stats.readCount = this.recipients.filter(r => r.isRead).length;
    this.stats.lastReadAt = new Date();
    
    // Update status if all recipients have read
    if (this.stats.readCount === this.stats.totalRecipients) {
      this.status = 'READ';
    }
  }
  
  return this.save();
};

notificationSchema.methods.addRecipient = function(walletAddress, name, role) {
  // Check if recipient already exists
  const existingRecipient = this.recipients.find(r => r.walletAddress === walletAddress);
  if (!existingRecipient) {
    this.recipients.push({
      walletAddress,
      name,
      role,
      isRead: false
    });
    this.stats.totalRecipients = this.recipients.length;
  }
  
  return this.save();
};

notificationSchema.methods.removeRecipient = function(walletAddress) {
  this.recipients = this.recipients.filter(r => r.walletAddress !== walletAddress);
  this.stats.totalRecipients = this.recipients.length;
  this.stats.readCount = this.recipients.filter(r => r.isRead).length;
  
  return this.save();
};

notificationSchema.methods.send = function() {
  if (this.status === 'DRAFT') {
    this.status = 'SENT';
    this.sentAt = new Date();
    
    // Set delivery settings defaults
    if (!this.deliverySettings.channels.length) {
      this.deliverySettings.channels = [
        { type: 'IN_APP', enabled: true },
        { type: 'EMAIL', enabled: true }
      ];
    }
  }
  
  return this.save();
};

notificationSchema.methods.cancel = function() {
  if (this.status === 'DRAFT' || this.status === 'SENT') {
    this.status = 'CANCELLED';
  }
  
  return this.save();
};

notificationSchema.methods.schedule = function(scheduleTime) {
  this.deliverySettings.scheduleTime = scheduleTime;
  this.deliverySettings.isScheduled = true;
  
  return this.save();
};

module.exports = mongoose.model('Notification', notificationSchema);